# Site Settings
title: "Lombard Academy"
description: "Personalized tutoring to help students unlock their academic potential."
baseurl: "/lombardacademy.github.io" 
url: "https://nicholasl25.github.io/lombardacademy.github.io/"
# Markdown Processing
markdown: kramdown

# Plugins (for GitHub Pages)
plugins:
  - jekyll-feed # Adds RSS feed for posts
  - jekyll-seo-tag # Adds SEO tags to improve search engine optimization
  - jekyll-sitemap # Generates a sitemap.xml file

# Exclusions
exclude:
  - "README.md"
  - "node_modules"
  - ".github"

# Configuration for Jekyll Themes (Optional)
# Uncomment if you want to use a Jekyll theme, like Minima
theme: minima

# Build Settings
future: true
show_drafts: false

# Custom Variables (Optional)
# You can add custom variables here to use in templates
author_name: "Nicholas Lombardo"
